# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(unique=True)),
                ('points', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('question_title', models.CharField(max_length=1000)),
                ('question_subject', models.CharField(max_length=1000)),
                ('question_options', jsonfield.fields.JSONField()),
                ('question_answer', models.CharField(max_length=1)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('won', models.BooleanField(default=False)),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gamer')),
            ],
        ),
        migrations.CreateModel(
            name='sessionlevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=1000, unique=True)),
                ('phone_number', models.IntegerField()),
                ('level', models.IntegerField(default=0)),
            ],
        ),
    ]
