# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180903_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
